### ISSUE TITLE
check.c doesn't compile on mac

### ISSUE THREAD

**Issue by shahzeb1** [xoreaxeaxeax/rosenbridge#10]
![image](https://user-images.githubusercontent.com/1383831/43988318-e8d9791e-9ce7-11e8-85c0-f8cc64f0583c.png)

Not sure if this is something by design.

Testing on a macOS 10.13.3.

**Comment by fmckeogh** [comment]
I had the same issue using 10.13.6.

**Comment by jwilk** [comment]
The code currently uses Linux-specific APIs.
It might be possible to port this to macOS, but somebody would have to write code specifically for this system.
