### ISSUE TITLE
List of affected Intel CPUs

### ISSUE THREAD

**Issue by E3V3A** [xoreaxeaxeax/rosenbridge#14]
@xoreaxeaxeax 
Do you know if there is a publicly available list of affected Intel CPU's somewhere?
Would your team, consider to make one available?

**Comment by different55** [comment]
This only affects a few VIA CPUs, no Intel or AMD CPUs are affected.

**Comment by E3V3A** [comment]
Still a list of what devices contain these affected CPU's would be useful. As you mentioned, that it is mostly old x86 embedded devices having this?
